"use client"

import {
  Activity,
  AlarmClock,
  AlertCircle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  Award,
  Banknote,
  Barcode,
  Battery,
  Beer,
  Bike,
  Bitcoin,
  Bluetooth,
  Bookmark,
  Building,
  Building2,
  Bus,
  Cake,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Check,
  CheckCircle,
  ChefHat,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  Clock,
  Cloud,
  CloudRain,
  CloudSnow,
  Coffee,
  Cog,
  Coins,
  Compass,
  Contact,
  Copy,
  CreditCard,
  Crosshair,
  Crown,
  Dice1,
  Dice6,
  DollarSign,
  Download,
  Droplets,
  Edit,
  Edit2,
  Edit3,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  FastForward,
  File,
  FileAudio,
  FileCode,
  FileImage,
  FileMinus,
  FilePlus,
  FileText,
  FileVideo,
  Filter,
  Fingerprint,
  Flame,
  Flower,
  Folder,
  FolderOpen,
  FolderPlus,
  Fuel,
  Gamepad,
  Gamepad2,
  Gift,
  Github,
  Globe,
  Grab,
  Hand,
  Hash,
  Headphones,
  Heart,
  HeartPulse,
  HelpCircle,
  Home,
  Hotel,
  IceCream,
  Info,
  Instagram,
  JapaneseYenIcon as Yen,
  Key,
  Laptop,
  Leaf,
  Lightbulb,
  Link,
  Linkedin,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  MicOff,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Move,
  Music,
  Navigation,
  Package,
  Package2,
  Paintbrush,
  Palette,
  Paperclip,
  Pause,
  PenTool,
  Percent,
  Phone,
  Pill,
  Pipette,
  Pizza,
  Plane,
  Play,
  Plus,
  PoundSterling,
  Power,
  Printer,
  QrCode,
  Radio,
  Receipt,
  RefreshCw,
  Rewind,
  RotateCcw,
  RotateCw,
  Ruler,
  Save,
  Scan,
  Scissors,
  Search,
  Send,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SkipBack,
  SkipForward,
  Sliders,
  Smartphone,
  SortAsc,
  SortDesc,
  Square,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Tablet,
  Tag,
  Tags,
  Target,
  Thermometer,
  ThermometerSun,
  ThumbsDown,
  ThumbsUp,
  Timer,
  ToggleLeft,
  ToggleRight,
  Train,
  Trash2,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Twitter,
  Unlock,
  Upload,
  Usb,
  User,
  UserCheck,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Utensils,
  Video,
  Volume2,
  VolumeX,
  Wallet,
  Watch,
  Wifi,
  WifiOff,
  Wind,
  Wine,
  Wrench,
  X,
  XCircle,
  Youtube,
  Zap,
} from "lucide-react"
import { getCustomIconById } from "@/lib/custom-icons-actions"
import { useEffect, useState } from "react"

const iconMap = {
  // Social & Communication
  link: Link,
  github: Github,
  twitter: Twitter,
  youtube: Youtube,
  instagram: Instagram,
  facebook: Facebook,
  linkedin: Linkedin,
  mail: Mail,
  phone: Phone,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  send: Send,
  share: Share,
  "share-2": Share2,

  // Navigation & Web
  globe: Globe,
  home: Home,
  "external-link": ExternalLink,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  "arrow-down": ArrowDown,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  menu: Menu,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,

  // User & Profile
  user: User,
  users: Users,
  "user-plus": UserPlus,
  "user-minus": UserMinus,
  "user-check": UserCheck,
  "user-x": UserX,
  contact: Contact,
  crown: Crown,
  shield: Shield,
  "shield-check": ShieldCheck,

  // System & Settings
  settings: Settings,
  cog: Cog,
  wrench: Wrench,
  "pen-tool": PenTool,
  sliders: Sliders,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  power: Power,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,

  // Files & Documents
  file: File,
  "file-text": FileText,
  "file-image": FileImage,
  "file-video": FileVideo,
  "file-audio": FileAudio,
  "file-code": FileCode,
  "file-plus": FilePlus,
  "file-minus": FileMinus,
  folder: Folder,
  "folder-open": FolderOpen,
  "folder-plus": FolderPlus,
  archive: Archive,
  download: Download,
  upload: Upload,
  paperclip: Paperclip,
  save: Save,

  // Media & Entertainment
  camera: Camera,
  video: Video,
  music: Music,
  headphones: Headphones,
  mic: Mic,
  "mic-off": MicOff,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  play: Play,
  pause: Pause,
  square: Square,
  "skip-forward": SkipForward,
  "skip-back": SkipBack,
  "fast-forward": FastForward,
  rewind: Rewind,
  radio: Radio,
  tv: Tv,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,

  // Actions & Status
  heart: Heart,
  star: Star,
  bookmark: Bookmark,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  "alert-circle": AlertCircle,
  info: Info,
  "help-circle": HelpCircle,
  search: Search,
  filter: Filter,
  "sort-asc": SortAsc,
  "sort-desc": SortDesc,

  // Time & Calendar
  calendar: Calendar,
  "calendar-days": CalendarDays,
  clock: Clock,
  timer: Timer,
  "alarm-clock": AlarmClock,
  watch: Watch,

  // Shopping & Commerce
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  "credit-card": CreditCard,
  banknote: Banknote,
  coins: Coins,
  wallet: Wallet,
  receipt: Receipt,
  tag: Tag,
  tags: Tags,
  percent: Percent,
  gift: Gift,
  truck: Truck,
  package: Package,
  "package-2": Package2,
  store: Store,

  // Location & Travel
  "map-pin": MapPin,
  map: Map,
  navigation: Navigation,
  compass: Compass,
  car: Car,
  plane: Plane,
  train: Train,
  bus: Bus,
  bike: Bike,
  fuel: Fuel,
  hotel: Hotel,
  building: Building,
  "building-2": Building2,

  // Weather & Nature
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  "cloud-rain": CloudRain,
  "cloud-snow": CloudSnow,
  zap: Zap,
  wind: Wind,
  thermometer: Thermometer,
  droplets: Droplets,
  flame: Flame,
  leaf: Leaf,
  "tree-pine": TreePine,
  flower: Flower,

  // Tools & Utilities
  scissors: Scissors,
  copy: Copy,
  clipboard: Clipboard,
  edit: Edit,
  "edit-2": Edit2,
  "edit-3": Edit3,
  paintbrush: Paintbrush,
  palette: Palette,
  pipette: Pipette,
  ruler: Ruler,
  move: Move,
  grab: Grab,
  hand: Hand,

  // Security & Privacy
  lock: Lock,
  unlock: Unlock,
  key: Key,
  eye: Eye,
  "eye-off": EyeOff,
  fingerprint: Fingerprint,

  // Gaming & Fun
  gamepad: Gamepad,
  "gamepad-2": Gamepad2,
  "dice-1": Dice1,
  "dice-6": Dice6,
  trophy: Trophy,
  award: Award,
  medal: Medal,
  target: Target,
  crosshair: Crosshair,

  // Health & Medical
  "heart-pulse": HeartPulse,
  activity: Activity,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  "thermometer-sun": ThermometerSun,

  // Food & Drink
  coffee: Coffee,
  wine: Wine,
  beer: Beer,
  utensils: Utensils,
  "chef-hat": ChefHat,
  pizza: Pizza,
  cake: Cake,
  "ice-cream": IceCream,

  // Miscellaneous
  lightbulb: Lightbulb,
  battery: Battery,
  wifi: Wifi,
  "wifi-off": WifiOff,
  bluetooth: Bluetooth,
  usb: Usb,
  printer: Printer,
  scan: Scan,
  "qr-code": QrCode,
  barcode: Barcode,
  hash: Hash,
  "at-sign": AtSign,
  "dollar-sign": DollarSign,
  euro: Euro,
  "pound-sterling": PoundSterling,
  yen: Yen,
  bitcoin: Bitcoin,
}

interface IconDisplayProps {
  iconType: "predefined" | "uploaded" | "custom"
  iconValue: string
  className?: string
}

export function IconDisplay({ iconType, iconValue, className = "h-5 w-5" }: IconDisplayProps) {
  const [customIconData, setCustomIconData] = useState<string | null>(null)

  useEffect(() => {
    if (iconType === "custom") {
      const loadCustomIcon = async () => {
        const icon = await getCustomIconById(Number.parseInt(iconValue))
        if (icon) {
          setCustomIconData(icon.data_url)
        }
      }
      loadCustomIcon()
    }
  }, [iconType, iconValue])

  if (iconType === "uploaded") {
    return (
      <img src={iconValue || "/placeholder.svg"} alt="Custom icon" className={`${className} object-cover rounded`} />
    )
  }

  if (iconType === "custom") {
    return (
      <img
        src={customIconData || "/placeholder.svg"}
        alt="Custom icon"
        className={`${className} object-cover rounded`}
      />
    )
  }

  const IconComponent = iconMap[iconValue as keyof typeof iconMap] || Link
  return <IconComponent className={className} />
}
